#!/bin/bash

if [ $# -ne 1 ]; then
        echo "Erreur! syntaxe: updater <version>"
        exit 1
fi

VERSION=$1
INSTALL_DIR="./server"
FILE="vs_server_linux-x64_${VERSION}.tar.gz"
DOWNLOAD_URL="https://cdn.vintagestory.at/gamefiles/stable/${FILE}"

stop_server() {
        echo "Stopping server..."
        $INSTALL_DIR/server.sh stop
}

download() {
        echo "Downloading version ${VERSION}..."
        wget $DOWNLOAD_URL
}

unzip(){
        echo "Unzipping files..."
        tar -zvxf $FILE -C $INSTALL_DIR
        rm $FILE
}

clean(){
        echo "Cleaning installation directory..."
        #cp $INSTALL_DIR/server.sh ./server.sh
        rm -rf $INSTALL_DIR/*
}

download

if [ -e "${INSTALL_DIR}/server.sh" ]; then
        echo "Found previous installation"
        stop_server
        clean
else
        echo "No previous installation found"

        if [ ! -d $INSTALL_DIR ]; then
                mkdir $INSTALL_DIR
        fi
fi

unzip